Upgrade de la version de twitter4j, mais NON TESTE EN REEL. Les exemples ne run pas : 	Exception in thread "main" java.lang.NoClassDefFoundError: twitter4j/internal/json/z_T4JInternalJSONImplFactory 		at com.twitter.hbc.twitter4j.v3.BaseTwitter4jClient.<init>(BaseTwitter4jClient.java:53) 		at com.twitter.hbc.twitter4j.v3.Twitter4jUserstreamClient.<init>(Twitter4jUserstreamClient.java:35) 		at fr.univaix.iut.pokebattle.tuse.TwitterUserStreamEasy.oauth(TwitterUserStreamEasy.java:68) 		at fr.univaix.iut.pokebattle.tuse.TwitterUserStreamEasy.oauth(TwitterUserStreamEasy.java:81) 		at fr.univaix.iut.pokebattle.tuse.TwitterUserStreamEasy.oauth(TwitterUserStreamEasy.java:91) 		at fr.univaix.iut.pokebattle.example.TwitterUserStreamEasyExample.main(TwitterUserStreamEasyExample.java:38) 		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) 		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 		at java.lang.reflect.Method.invoke(Method.java:606) 		at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120) 	Caused by: java.lang.ClassNotFoundException: twitter4j.internal.json.z_T4JInternalJSONImplFactory 		at java.net.URLClassLoader$1.run(URLClassLoader.java:366) 		at java.net.URLClassLoader$1.run(URLClassLoader.java:355) 		at java.security.AccessController.doPrivileged(Native Method) 		at java.net.URLClassLoader.findClass(URLClassLoader.java:354) 		at java.lang.ClassLoader.loadClass(ClassLoader.java:425) 		at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) 		at java.lang.ClassLoader.loadClass(ClassLoader.java:358) 		... 11 more